# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        dc:
        - dmd-latest
        - dmd-2.099.0 # must be supported for GDC support
        - dmd-2.092.0 # minimum working at point of writing
        - ldc-latest
        - ldc-1.27.0
        - ldc-1.23.0
        exclude:
        # linker errors with unit-threaded on dmd-latest with 2.101 for some reason
        - os: windows-latest
          dc: dmd-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1.3.0
      with:
        compiler: ${{ matrix.dc }}

    - name: 'Build & Test'
      run: |
        dub build
        dub test
